"""Domain package: importing registers projection handlers for every domain."""
from apm.domains import (  # noqa: F401
    approvals,
    assets,
    automations,
    conversations,
    events_api,
    features,
    items,
    members,
    nl,
    notifications,
    ontology,
    ontology_cq,
    ontology_learn,
    ontology_pack,
    ontology_versions,
    orchestrator_api,
    projects,
    runs,
    stream,
    system,
    template_packs,
    users,
    webhooks,
)
