"""Replay fixtures: deterministic response templates keyed by (role, node).

Templates embed run context so injected constraints change outputs — this is
what makes "interrupt → inject → resume → artifact contains constraint"
verifiable in CI without a real model. Recordings from `record` mode override
templates (same key space).
"""
from __future__ import annotations

from typing import Any

from apm import config


def _constraints_block(context: dict[str, Any]) -> str:
    constraints = context.get("constraints") or []
    if not constraints:
        return "（无）"
    return "\n".join(f"- {c}" for c in constraints)


def _recorded(key: str) -> str | None:
    path = config.settings.fixtures_dir / "recordings.yaml"
    if not path.exists():
        return None
    import yaml

    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return data.get(key)


def render(role: str, node: str, context: dict[str, Any]) -> str:
    key = f"{role}/{node}"
    recorded = _recorded(key)
    if recorded is not None:
        return recorded
    fn = _TEMPLATES.get(key)
    if fn is None:
        raise KeyError(f"no replay fixture for '{key}'")
    return fn(context)


def _pm_analyze(c):
    instr = c.get("instruction") or "（未提供指令）"
    return (
        "## 需求分析\n"
        f"- 核心诉求：{instr}\n"
        "- 干系人：单人开发者（人）+ 角色 Agent\n"
        "- 待澄清点：验收标准与边界（将在 PRD 中定义）\n"
        f"- 已识别约束：{_constraints_block(c)}\n"
    )


def _pm_draft(c):
    name = c.get("project_name", "本项目")
    instr = c.get("instruction") or "（待补充）"
    return (
        f"# PRD：{name}\n\n"
        "## 1. 背景与目标\n"
        f"{instr}\n\n"
        "## 2. 用户故事\n"
        "1. 作为用户，我希望提交一句话需求，以便快速启动项目；\n"
        "2. 作为用户，我希望审批 Agent 产出的 PRD，以便控制方向；\n"
        "3. 作为用户，我希望随时打断并纠正 Agent，以便纠偏成本最低。\n\n"
        "## 3. 功能范围\n"
        "- 需求池与 PRD 起草\n- 阶段门审批\n- 任务看板与 Agent 派工\n\n"
        "## 4. 非目标（边界）\n- 不做多人权限体系；不做移动端。\n\n"
        "## 5. 补充约束\n"
        f"{_constraints_block(c)}\n\n"
        "## 6. 验收标准\n"
        "- PRD 覆盖上述用户故事；\n- 所有补充约束逐条体现在功能范围或约束节；\n"
        "- 通过 PRD 评审（gate: prd_review）。\n"
    )


def _planner_analyze(c):
    return (
        "## 计划分析\n"
        f"- 输入 PRD 已获批准；约束：{_constraints_block(c)}\n"
        "- 分解策略：按功能范围切 12 个任务，建立依赖链，高/中/低优先级混合。\n"
    )


def _planner_draft(c):
    name = c.get("project_name", "本项目")
    tasks = [
        ("T1", "搭建项目骨架与内容仓", "high", 4, []),
        ("T2", "需求池与一句话需求录入", "high", 3, ["T1"]),
        ("T3", "PRD 起草流水线（PM-Agent 子图）", "high", 8, ["T2"]),
        ("T4", "阶段门与审批挂起机制", "high", 6, ["T3"]),
        ("T5", "打断-注入-恢复链路", "high", 6, ["T4"]),
        ("T6", "任务看板投影与过滤", "medium", 5, ["T4"]),
        ("T7", "导入解析模块", "medium", 6, ["T1"]),
        ("T8", "数据校验与清洗", "medium", 5, ["T7"]),
        ("T9", "报告模板引擎", "medium", 6, ["T8"]),
        ("T10", "周报导出（Markdown/CSV）", "low", 4, ["T9"]),
        ("T11", "审计事件流查询与导出", "low", 4, ["T6"]),
        ("T12", "端到端冒烟与文档", "low", 5, ["T10", "T11"]),
    ]
    lines = [f"# WBS：{name}", "", "## 任务分解", ""]
    wbs = []
    for tid, title, pri, est, deps in tasks:
        dep_str = f"（依赖 {', '.join(deps)}）" if deps else ""
        lines.append(f"- **{tid}** {title} · 优先级 {pri} · {est}h {dep_str}")
        wbs.append(
            {"id": tid, "title": f"{tid} {title}", "priority": pri,
             "estimate_hours": est, "depends_on": deps}
        )
    import json

    lines += [
        "",
        f"## 补充约束\n{_constraints_block(c)}",
        "",
        "## 工作项清单（系统据此创建）",
        "",
        "```wbs",
        json.dumps(wbs, ensure_ascii=False, indent=2),
        "```",
    ]
    return "\n".join(lines)


def _dev_analyze(c):
    return (
        "## 实现分析\n"
        f"- 任务：{c.get('item_title', c.get('instruction', '开发任务'))}\n"
        f"- 约束：{_constraints_block(c)}\n"
        "- 交付物：Markdown 补丁文档（无沙箱，不执行命令）。\n"
    )


def _dev_draft(c):
    item = c.get("item_title") or c.get("instruction") or "任务"
    code_name = (c.get("item_id") or "task") + ".py"
    return (
        f"# 补丁：{item}\n\n"
        "## 变更说明\n"
        f"按 L3 指令实现 {item}；用户约束已纳入：{_constraints_block(c)}\n\n"
        f"## 文件：code/{code_name}\n\n"
        "```python\n"
        f"'''{item} — generated by dev-agent (replay)'''\n"
        "def handle(data):\n"
        "    # 约束逐条落实\n"
        "    return {'ok': True}\n"
        "```\n\n"
        "## 自测\n- 静态检查通过；示例输入返回 ok。\n"
    )


def _release_analyze(c):
    return (
        "## 交付分析\n"
        f"- 工件清单：{len(c.get('artifacts', []) or [])} 个\n"
        f"- 轨迹摘要：{c.get('runs_digest', '（无运行记录）')}\n"
    )


def _release_draft(c):
    name = c.get("project_name", "本项目")
    arts = c.get("artifacts") or []
    art_lines = "\n".join(f"- `{a['path']}`（{a.get('versions', 1)} 版）" for a in arts) or "（无）"
    return (
        f"# Release Notes：{name} v0.1\n\n"
        "## 变更列表\n"
        f"{art_lines}\n\n"
        "## 人机协作摘要\n"
        f"{c.get('runs_digest', '（无运行记录）')}\n\n"
        "## 验收结论\n- 阶段门全部通过；补充约束已验证。\n\n"
        "## 遗留事项\n- 无阻塞事项。\n"
    )


def _qa_analyze(c):
    return "## 测试分析\n- 依据验收标准设计用例；优先检索测试库既有回归套件。\n"


def _qa_draft(c):
    return (
        "# 测试报告\n\n"
        "## 用例结果\n"
        "| 用例 | 结果 |\n| --- | --- |\n| 一句话需求建项 | ✅ 通过 |\n"
        "| PRD 审批后计划接续 | ✅ 通过 |\n| 打断-恢复 | ✅ 通过 |\n"
        f"\n## 回归套件\n- {_constraints_block(c)}\n\n## 缺陷\n- 无阻塞缺陷。\n"
    )


def _arch_analyze(c):
    return "## 设计分析\n- 模块划分：内核（事件/投影）/ 运行时 / 编排 / 前端。\n"


def _arch_draft(c):
    return (
        "# 系统设计\n\n## 模块划分\n- 事件内核；Agent Runtime；Orchestrator；WebUI。\n\n"
        "## 数据模型\n- events（唯一事实源）+ 投影表 + 内容仓 Git。\n\n"
        "## 技术选型\n- FastAPI/LangGraph/SQLite/React。\n"
    )


def _self_check(c):
    draft = c.get("draft") or ""
    issues = []
    if len(draft.strip()) < 50:
        issues.append("产出过短")
    return "PASS" if not issues else "ISSUES: " + "; ".join(issues)


def _ontology_curator_curate(c):
    """LLM 层回放模板（08 §8.4）：从注入上下文确定性地产出建议候选 JSON。

    真实行为在 openai 模式下由提示词驱动；回放层按同输入给同输出，
    保证 learn-llm 在 CI 无模型可测。启发：命名覆盖的工件→资产沉淀去向。
    """
    import json

    suggestions = []
    for ak in c.get("artifact_kinds_without_deposit", []):
        kind_id = ak["id"]
        for asset_kind in c.get("asset_kinds", []):
            if kind_id != asset_kind and kind_id in asset_kind:
                suggestions.append({
                    "op": "wire_deposit",
                    "concept": ak["concept"],
                    "artifact_kind": kind_id,
                    "deposits_to": asset_kind,
                    "confidence": 0.72,
                    "rationale": f"资产类型 {asset_kind} 命名覆盖工件 {kind_id}，"
                                 f"且该工件尚无沉淀去向（LLM 层建议，人审后生效）",
                })
                break
    return json.dumps({"candidates": suggestions}, ensure_ascii=False)


_TEMPLATES = {
    "pm-agent/analyze": _pm_analyze,
    "pm-agent/draft": _pm_draft,
    "pm-agent/self_check": _self_check,
    "planner-agent/analyze": _planner_analyze,
    "planner-agent/draft": _planner_draft,
    "planner-agent/self_check": _self_check,
    "dev-agent/analyze": _dev_analyze,
    "dev-agent/draft": _dev_draft,
    "dev-agent/self_check": _self_check,
    "release-agent/analyze": _release_analyze,
    "release-agent/draft": _release_draft,
    "release-agent/self_check": _self_check,
    "qa-agent/analyze": _qa_analyze,
    "qa-agent/draft": _qa_draft,
    "qa-agent/self_check": _self_check,
    "architect-agent/analyze": _arch_analyze,
    "architect-agent/draft": _arch_draft,
    "architect-agent/self_check": _self_check,
    "ontology-curator/curate": _ontology_curator_curate,
}
